VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "ctalebS" do |server|
    server.vm.hostname = "ctalebS"
    server.vm.network "private_network", ip: "192.168.58.110", netmask: "255.255.255.0"
    server.vm.provider "virtualbox" do |vb|
      vb.customize [
        'modifyvm', :id,
        '--name', 'ctalebS',
        '--natdnshostresolver1', 'on',
        '--memory', '512',
        '--cpus', '1'
      ]
    end
  end

  config.vm.define "ctalebSW" do |worker|
    worker.vm.hostname = "ctalebSW"
    worker.vm.network "private_network", ip: "192.168.58.111", netmask: "255.255.255.0"
    worker.vm.provider "virtualbox" do |vb|
      vb.customize [
        'modifyvm', :id,
        '--name', 'ctalebSW',
        '--natdnshostresolver1', 'on',
        '--memory', '512',
        '--cpus', '1'
      ]
    end
  end
end